// Auto-generates new clone brands based on gap detection
module.exports = function spawnPhantomBrand(trend) {
  return {
    name: `${trend.replace(/\s+/g, '')}GPT`,
    domain: `${trend.toLowerCase().replace(/\s+/g, '')}.vercel.app`,
    persona: `${trend.split(' ')[0]}Bot`,
    tier: "free",
    autoGenerated: true
  };
};